python notebooks/evaluate_notebook.py --ckpt_dir=/group/jug/ashesh/training/denoisplit/2502/D26-M3-S0-L0/3 --mmse_count=10 --MIXING_WEIGHT=0.1 --data_dir=/group/jug/ashesh/data/diffsplit_HT_LIF/500ms/Ch_B-Ch_D-Ch_BD/ --image_size_for_grid_centers=256 --custom_image_size=512
python notebooks/evaluate_notebook.py --ckpt_dir=/group/jug/ashesh/training/denoisplit/2502/D26-M3-S0-L0/3 --mmse_count=10 --MIXING_WEIGHT=0.2 --data_dir=/group/jug/ashesh/data/diffsplit_HT_LIF/500ms/Ch_B-Ch_D-Ch_BD/ --image_size_for_grid_centers=256 --custom_image_size=512
python notebooks/evaluate_notebook.py --ckpt_dir=/group/jug/ashesh/training/denoisplit/2502/D26-M3-S0-L0/3 --mmse_count=10 --MIXING_WEIGHT=0.3 --data_dir=/group/jug/ashesh/data/diffsplit_HT_LIF/500ms/Ch_B-Ch_D-Ch_BD/ --image_size_for_grid_centers=256 --custom_image_size=512
python notebooks/evaluate_notebook.py --ckpt_dir=/group/jug/ashesh/training/denoisplit/2502/D26-M3-S0-L0/3 --mmse_count=10 --MIXING_WEIGHT=0.4 --data_dir=/group/jug/ashesh/data/diffsplit_HT_LIF/500ms/Ch_B-Ch_D-Ch_BD/ --image_size_for_grid_centers=256 --custom_image_size=512
python notebooks/evaluate_notebook.py --ckpt_dir=/group/jug/ashesh/training/denoisplit/2502/D26-M3-S0-L0/3 --mmse_count=10 --MIXING_WEIGHT=0.5 --data_dir=/group/jug/ashesh/data/diffsplit_HT_LIF/500ms/Ch_B-Ch_D-Ch_BD/ --image_size_for_grid_centers=256 --custom_image_size=512
python notebooks/evaluate_notebook.py --ckpt_dir=/group/jug/ashesh/training/denoisplit/2502/D26-M3-S0-L0/3 --mmse_count=10 --MIXING_WEIGHT=0.6 --data_dir=/group/jug/ashesh/data/diffsplit_HT_LIF/500ms/Ch_B-Ch_D-Ch_BD/ --image_size_for_grid_centers=256 --custom_image_size=512
python notebooks/evaluate_notebook.py --ckpt_dir=/group/jug/ashesh/training/denoisplit/2502/D26-M3-S0-L0/3 --mmse_count=10 --MIXING_WEIGHT=0.7 --data_dir=/group/jug/ashesh/data/diffsplit_HT_LIF/500ms/Ch_B-Ch_D-Ch_BD/ --image_size_for_grid_centers=256 --custom_image_size=512
python notebooks/evaluate_notebook.py --ckpt_dir=/group/jug/ashesh/training/denoisplit/2502/D26-M3-S0-L0/3 --mmse_count=10 --MIXING_WEIGHT=0.8 --data_dir=/group/jug/ashesh/data/diffsplit_HT_LIF/500ms/Ch_B-Ch_D-Ch_BD/ --image_size_for_grid_centers=256 --custom_image_size=512
python notebooks/evaluate_notebook.py --ckpt_dir=/group/jug/ashesh/training/denoisplit/2502/D26-M3-S0-L0/3 --mmse_count=10 --MIXING_WEIGHT=0.9 --data_dir=/group/jug/ashesh/data/diffsplit_HT_LIF/500ms/Ch_B-Ch_D-Ch_BD/ --image_size_for_grid_centers=256 --custom_image_size=512


python notebooks/evaluate_notebook.py --ckpt_dir=/group/jug/ashesh/training/denoisplit/2502/D26-M3-S0-L0/3 --mmse_count=10  --data_dir=/group/jug/ashesh/data/diffsplit_HT_LIF/500ms/Ch_B-Ch_D-Ch_BD/ --notebook=/home/ashesh.ashesh/code/denoiSplit/notebooks/EvaluateRealInput.ipynb --custom_image_size=512 --image_size_for_grid_centers=256